#!/bin/sh

bspc monitor -d 1 2 3

bspc config split_ratio 0.5

bspc config focused_border_color "#935ea1"
bspc config normal_border_color "#2c1c30"
bspc config active_border_color "#2c1c30"

# overlapping borders
bw=1
bspc config border_width $bw
bspc config window_gap -$bw
for side in top right bottom left; do
	bspc config ${side}_padding $bw
done

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr -solid "#2c1c30"

polybar mybar &
sxhkd &
